export const CHEATSHEET_DATA = {
  headings: [
    { name: 'Heading 1', syntax: '# Heading 1', output: <p className="text-base font-bold text-zinc-900 dark:text-white">Heading 1</p> },
    { name: 'Heading 2', syntax: '## Heading 2', output: <p className="text-sm font-bold text-zinc-800 dark:text-zinc-100">Heading 2</p> },
    { name: 'Heading 3', syntax: '### Heading 3', output: <p className="text-xs font-bold text-zinc-700 dark:text-zinc-200">Heading 3</p> },
    { name: 'Heading 4', syntax: '#### Heading 4', output: <p className="text-xs font-semibold text-zinc-600 dark:text-zinc-300">Heading 4</p> },
    { name: 'Heading 5', syntax: '##### Heading 5', output: <p className="text-[11px] font-semibold text-zinc-500 dark:text-zinc-400">Heading 5</p> },
    { name: 'Heading 6', syntax: '###### Heading 6', output: <p className="text-[11px] font-semibold text-zinc-400 dark:text-zinc-500">Heading 6</p> },
    { name: 'Alt Heading 1', syntax: 'Heading 1\n=========', output: <p className="text-base font-bold text-zinc-900 dark:text-white">Heading 1</p> },
    { name: 'Alt Heading 2', syntax: 'Heading 2\n---------', output: <p className="text-sm font-bold text-zinc-800 dark:text-zinc-100">Heading 2</p> },
  ],
  emphasis: [
    { name: 'Bold', syntax: '**bold** or __bold__', output: <strong className="font-bold">bold</strong> },
    { name: 'Italic', syntax: '*italic* or _italic_', output: <em className="italic">italic</em> },
    { name: 'Bold + Italic', syntax: '***bold italic***', output: <strong><em>bold italic</em></strong> },
    { name: 'Strikethrough', syntax: '~~strikethrough~~', output: <del className="line-through text-zinc-400">strikethrough</del> },
    { name: 'Highlight', syntax: '==highlighted==', output: <mark className="bg-yellow-200 dark:bg-yellow-800 px-0.5 rounded">highlighted</mark> },
    { name: 'Subscript', syntax: 'H~2~O', output: <span>H<sub>2</sub>O</span> },
    { name: 'Superscript', syntax: 'X^2^', output: <span>X<sup>2</sup></span> },
    { name: 'Blockquote', syntax: '> Quote text', output: <blockquote className="border-l-2 border-zinc-300 dark:border-zinc-600 pl-2 italic text-zinc-500 dark:text-zinc-400 text-[11px]">Quote text</blockquote> },
    { name: 'Nested Quote', syntax: '> Quote\n>> Nested', output: <blockquote className="border-l-2 border-zinc-300 dark:border-zinc-600 pl-2 italic text-zinc-500 dark:text-zinc-400 text-[11px]">Quote<blockquote className="border-l-2 border-zinc-300 dark:border-zinc-600 pl-2 mt-0.5">Nested</blockquote></blockquote> },
    { name: 'Horizontal Rule', syntax: '--- or *** or ___', output: <hr className="border-zinc-300 dark:border-zinc-700 my-1" /> },
  ],
  lists: [
    { name: 'Unordered List', syntax: '- Item\n- Item\n- Item', output: <ul className="list-disc pl-4 text-[11px] space-y-0.5"><li>Item</li><li>Item</li><li>Item</li></ul> },
    { name: 'Ordered List', syntax: '1. First\n2. Second\n3. Third', output: <ol className="list-decimal pl-4 text-[11px] space-y-0.5"><li>First</li><li>Second</li><li>Third</li></ol> },
    { name: 'Nested List', syntax: '- Item\n  - Nested\n  - Nested', output: <ul className="list-disc pl-4 text-[11px]"><li>Item<ul className="list-disc pl-4"><li>Nested</li><li>Nested</li></ul></li></ul> },
    { name: 'Task List', syntax: '- [x] Done\n- [ ] Todo\n- [ ] Todo', output: <ul className="list-none pl-0 text-[11px] space-y-0.5"><li><input type="checkbox" checked readOnly className="mr-1 cursor-default align-middle" />Done</li><li><input type="checkbox" readOnly className="mr-1 cursor-default align-middle" />Todo</li></ul> },
    { name: 'Alt Unordered', syntax: '* Item\n+ Item\n- Item', output: <ul className="list-disc pl-4 text-[11px] space-y-0.5"><li>Item</li><li>Item</li><li>Item</li></ul> },
    { name: 'Definition List', syntax: 'Term\n: Definition', output: <dl className="text-[11px]"><dt className="font-semibold text-zinc-800 dark:text-zinc-200">Term</dt><dd className="pl-3 text-zinc-500 dark:text-zinc-400">Definition</dd></dl> },
  ],
  links_images: [
    { name: 'Inline Link', syntax: '[text](https://url.com)', output: <a className="text-[#0969da] dark:text-[#58a6ff] underline text-[11px]">text</a> },
    { name: 'Link with Title', syntax: '[text](url "Title")', output: <a className="text-[#0969da] dark:text-[#58a6ff] underline text-[11px]" title="Title">text</a> },
    { name: 'Reference Link', syntax: '[text][ref]\n\n[ref]: https://url.com', output: <a className="text-[#0969da] dark:text-[#58a6ff] underline text-[11px]">text</a> },
    { name: 'Auto Link', syntax: '<https://url.com>', output: <a className="text-[#0969da] dark:text-[#58a6ff] underline text-[11px]">https://url.com</a> },
    { name: 'Email Link', syntax: '<user@example.com>', output: <a className="text-[#0969da] dark:text-[#58a6ff] underline text-[11px]">user@example.com</a> },
    { name: 'Image', syntax: '![alt](image.png)', output: <span className="text-[11px] text-zinc-400 dark:text-zinc-500 italic">image.png</span> },
    { name: 'Image with Title', syntax: '![alt](img.png "Title")', output: <span className="text-[11px] text-zinc-400 dark:text-zinc-500 italic">img.png</span> },
    { name: 'Image Link', syntax: '[![alt](img.png)](url)', output: <span className="text-[11px] text-[#0969da] dark:text-[#58a6ff] underline italic">linked image</span> },
  ],
  code: [
    { name: 'Inline Code', syntax: '`code here`', output: <code className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 px-1 py-0.5 rounded font-mono text-[11px] text-zinc-700 dark:text-zinc-300">code here</code> },
    { name: 'Code Block', syntax: '```\ncode here\n```', output: <pre className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 p-1.5 rounded font-mono text-[10px] text-zinc-700 dark:text-zinc-300">code here</pre> },
    { name: 'JS Code Block', syntax: '```javascript\nconst x = 1;\n```', output: <pre className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 p-1.5 rounded font-mono text-[10px] text-zinc-700 dark:text-zinc-300">const x = 1;</pre> },
    { name: 'Python Block', syntax: '```python\nprint("hi")\n```', output: <pre className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 p-1.5 rounded font-mono text-[10px] text-zinc-700 dark:text-zinc-300">{'print("hi")'}</pre> },
    { name: 'Bash Block', syntax: '```bash\nnpm install\n```', output: <pre className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 p-1.5 rounded font-mono text-[10px] text-zinc-700 dark:text-zinc-300">npm install</pre> },
    { name: 'Indented Block', syntax: '    code here\n    (4 spaces)', output: <pre className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 p-1.5 rounded font-mono text-[10px] text-zinc-700 dark:text-zinc-300">code here</pre> },
  ],
  tables: [
    { name: 'Basic Table', syntax: '| A | B |\n|---|---|\n| 1 | 2 |', output: <table className="border-collapse text-[10px] w-full"><thead className="bg-zinc-100 dark:bg-zinc-800"><tr><th className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5">A</th><th className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5">B</th></tr></thead><tbody><tr><td className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5">1</td><td className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5">2</td></tr></tbody></table> },
    { name: 'Align Left', syntax: '| A |\n|:--|\n| 1 |', output: <table className="border-collapse text-[10px]"><thead className="bg-zinc-100 dark:bg-zinc-800"><tr><th className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5 text-left">A</th></tr></thead><tbody><tr><td className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5 text-left">1</td></tr></tbody></table> },
    { name: 'Align Center', syntax: '| A |\n|:--:|\n| 1 |', output: <table className="border-collapse text-[10px]"><thead className="bg-zinc-100 dark:bg-zinc-800"><tr><th className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5 text-center">A</th></tr></thead><tbody><tr><td className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5 text-center">1</td></tr></tbody></table> },
    { name: 'Align Right', syntax: '| A |\n|--:|\n| 1 |', output: <table className="border-collapse text-[10px]"><thead className="bg-zinc-100 dark:bg-zinc-800"><tr><th className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5 text-right">A</th></tr></thead><tbody><tr><td className="border border-zinc-200 dark:border-zinc-700 px-2 py-0.5 text-right">1</td></tr></tbody></table> },
  ],
  extras: [
    { name: 'Keyboard Key', syntax: '<kbd>Ctrl</kbd>+<kbd>S</kbd>', output: <span><kbd className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-600 px-1 rounded text-[10px] font-mono">Ctrl</kbd><span className="text-[10px] mx-0.5">+</span><kbd className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-600 px-1 rounded text-[10px] font-mono">S</kbd></span> },
    { name: 'Footnote', syntax: 'Text[^1]\n\n[^1]: Note', output: <span className="text-[11px]">Text<sup className="text-[#0969da] dark:text-[#58a6ff] text-[9px]">1</sup></span> },
    { name: 'Emoji Shortcode', syntax: ':rocket: :fire: :star:', output: <span className="text-base">🚀 🔥 ⭐</span> },
    { name: 'HTML Comment', syntax: '<!-- hidden comment -->', output: <span className="text-[11px] text-zinc-400 dark:text-zinc-500 italic">(not rendered)</span> },
    { name: 'Escape Character', syntax: '\\*not italic\\*', output: <span className="text-[11px]">*not italic*</span> },
    { name: 'Line Break', syntax: 'Line 1  \nLine 2 (2 spaces)', output: <span className="text-[11px]">Line 1<br />Line 2</span> },
    { name: 'Details / Summary', syntax: '<details>\n<summary>Click</summary>\nContent\n</details>', output: <details className="text-[11px] cursor-pointer"><summary className="font-semibold text-zinc-700 dark:text-zinc-300">Click</summary><span className="text-zinc-500 dark:text-zinc-400 pl-2">Content</span></details> },
    { name: 'Abbreviation', syntax: '*[HTML]: HyperText\nHTML', output: <abbr title="HyperText" className="text-[11px] underline decoration-dotted cursor-help">HTML</abbr> },
  ],
}
